services:
  db:
    image: mariadb:11.6
    container_name: legacy-db
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: legacy_db
      MYSQL_USER: maria
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    tty: true
    restart: always
    command: --ssl=0
    healthcheck:  # コンテナの起動チェック
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: legacy-phpmyadmin
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      # - db
      db:
        condition: service_healthy
